Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Readme  = Join-Path (Get-Location) "README.md"
$Results = Join-Path (Get-Location) "results"
$Figures = Join-Path $Results "figures"
$SummaryCsv = Join-Path $Results "summary.csv"

if (!(Test-Path $Readme)) { throw "README.md no existe en la raíz." }
if (!(Test-Path $SummaryCsv)) { throw "No existe results/summary.csv. No se puede publicar sin datos." }

$ts = Get-Date -Format "yyyyMMdd_HHmmss"
$bak = Join-Path (Get-Location) ("README.backup_{0}.md" -f $ts)
Copy-Item -Force $Readme $bak

function Normalize-Cell([object]$v) {
  if ($null -eq $v) { return "N/A" }
  $s = "$v".Trim()
  if ($s -eq "" -or $s -eq "None" -or $s -eq "null") { return "N/A" }
  return $s
}

function Remove-NoiseLines([string]$text) {
  $lines = $text -split "`n"
  $out = New-Object System.Collections.Generic.List[string]
  foreach ($ln in $lines) {
    $t = $ln.Trim()
    if ($t -match '^Add-Content\s+-Path\s+.*README\.content\.txt') { continue }
    if ($t -match '^`"\s*$') { continue }
    if ($t -eq "ash") { continue }
    $out.Add($ln) | Out-Null
  }
  return ($out -join "`n")
}

function Remove-Block([string]$text, [string]$start, [string]$end) {
  $s = [regex]::Escape($start)
  $e = [regex]::Escape($end)
  if ($text -match $s -and $text -match $e) {
    $pattern = $s + ".*?" + $e
    return [regex]::Replace($text, $pattern, "", "Singleline")
  }
  return $text
}

$rows = Import-Csv -Path $SummaryCsv
$cols = @{}
if ($rows.Count -gt 0) {
  foreach ($p in $rows[0].PSObject.Properties.Name) { $cols[$p] = $true }
}

$preferred = @(
  "scenario_id","N0","population",
  "o2_storage_days","water_storage_days",
  "o2_local_fraction","water_local_fraction","water_recovery_fraction",
  "launch_window_days","missed_window_probability",
  "collapsed","collapse_day","dose_msv"
)

$headers = New-Object System.Collections.Generic.List[string]
foreach ($h in $preferred) {
  if ($cols.ContainsKey($h)) { $headers.Add($h) | Out-Null }
}
if ($headers.Count -eq 0) { $headers.Add("scenario_id") | Out-Null }

$mdTable = New-Object System.Collections.Generic.List[string]
$mdTable.Add("| " + ($headers -join " | ") + " |") | Out-Null
$mdTable.Add("| " + (($headers | ForEach-Object { "---" }) -join " | ") + " |") | Out-Null

foreach ($r in $rows) {
  $vals = @()
  foreach ($h in $headers) { $vals += (Normalize-Cell $r.$h) }
  $mdTable.Add("| " + ($vals -join " | ") + " |") | Out-Null
}

$statements = New-Object System.Collections.Generic.List[string]
foreach ($r in $rows) {
  $sid = Normalize-Cell $r.scenario_id
  $collapsed = if ($cols.ContainsKey("collapsed")) { Normalize-Cell $r.collapsed } else { "N/A" }
  $day = if ($cols.ContainsKey("collapse_day")) { Normalize-Cell $r.collapse_day } else { "N/A" }
  $dose = if ($cols.ContainsKey("dose_msv")) { Normalize-Cell $r.dose_msv } else { "N/A" }

  $n0 = if ($cols.ContainsKey("N0")) { Normalize-Cell $r.N0 } elseif ($cols.ContainsKey("population")) { Normalize-Cell $r.population } else { "N/A" }
  $o2c = if ($cols.ContainsKey("o2_local_fraction")) { Normalize-Cell $r.o2_local_fraction } else { "N/A" }
  $wac = if ($cols.ContainsKey("water_local_fraction")) { Normalize-Cell $r.water_local_fraction } else { "N/A" }
  $win = if ($cols.ContainsKey("launch_window_days")) { Normalize-Cell $r.launch_window_days } else { "N/A" }
  $miss = if ($cols.ContainsKey("missed_window_probability")) { Normalize-Cell $r.missed_window_probability } else { "N/A" }

  $statements.Add(("- {0}: N0={1}, O2_local_fraction={2}, Water_local_fraction={3}, launch_window_days={4}, missed_window_probability={5} -> collapsed={6} at day={7}; dose_msv={8}" -f `
    $sid,$n0,$o2c,$wac,$win,$miss,$collapsed,$day,$dose
  )) | Out-Null
}

$figureLines = New-Object System.Collections.Generic.List[string]
if (Test-Path $Figures) {
  $pngs = @(Get-ChildItem -Path (Join-Path $Figures "*.png") -ErrorAction SilentlyContinue | Sort-Object Name)
  if ($pngs.Count -gt 0) {
    $figureLines.Add("") | Out-Null
    $figureLines.Add("### Figures") | Out-Null
    foreach ($p in $pngs) {
      $rel = ("results/figures/{0}" -f $p.Name)
      $figureLines.Add(("- ![{0}]({1})" -f $p.BaseName, $rel)) | Out-Null
    }
  }
}

$markerStart = "<!-- PUBLISHED_RESULTS_START -->"
$markerEnd   = "<!-- PUBLISHED_RESULTS_END -->"

# IMPORTANTE: usar array + concatenación (evita problemas de parseo)
$block = @()
$block += $markerStart
$block += "## Published Results (Reproducible)"
$block += ""
$block += "Source of truth: results/summary.csv (generated by running the public model)."
$block += ""
$block += "Reproduce (PowerShell):"
$block += "    python -m scripts.run_scenarios"
$block += ""
$block += "Artifacts:"
$block += "- results/summary.csv"
$block += "- results/summary.md"
if (Test-Path $Figures) { $block += "- results/figures/*.png (if generated)" }
$block += ""
$block += "### Summary table (from results/summary.csv)"
$block += $mdTable
if ($figureLines.Count -gt 0) { $block += $figureLines }
$block += ""
$block += "### Falsifiable outcome statements"
$block += $statements
$block += ""
$block += "Notes:"
$block += "- If collapse_day is N/A, the run ended without emitting a collapse day for that scenario (model output), not a manual edit."
$block += $markerEnd

$blockText = ($block -join "`n")

$readmeText = Get-Content $Readme -Raw
$readmeText = Remove-Block $readmeText "<!-- RESULTS_BEGIN -->" "<!-- RESULTS_END -->"
$readmeText = Remove-Block $readmeText "<!-- RESULTS_BLOCK_BEGIN -->" "<!-- RESULTS_BLOCK_END -->"
$readmeText = Remove-NoiseLines $readmeText

if ($readmeText -match [regex]::Escape($markerStart) -and $readmeText -match [regex]::Escape($markerEnd)) {
  $pattern = [regex]::Escape($markerStart) + ".*?" + [regex]::Escape($markerEnd)
  $readmeText = [regex]::Replace($readmeText, $pattern, $blockText, "Singleline")
} else {
  $readmeText = $readmeText.TrimEnd() + "`n`n" + $blockText + "`n"
}

[System.IO.File]::WriteAllText($Readme, $readmeText, (New-Object System.Text.UTF8Encoding($false)))

git add -- README.md $bak results/summary.csv results/summary.md 2>$null | Out-Null
git add -- results/figures/*.png 2>$null | Out-Null

$cached = @(git diff --name-only --cached)
if ($cached.Count -eq 0) {
  Write-Host "OK: nothing to commit." -ForegroundColor Green
  git status -sb | Out-Host
  exit 0
}

git commit -m "docs: clean README + rebuild published-results block from results/summary.csv (PS5.1-safe)" | Out-Host
git push | Out-Host

Write-Host ""
Write-Host ("FINAL: README cleaned (backup: {0}) and published-results rebuilt." -f $bak) -ForegroundColor Green